### ISSUE TITLE
Release an 0.29 with #1245 included

### ISSUE THREAD

**Issue by hdevalence** [informalsystems/tendermint-rs#1263]
### Description

Hi, it'd be great to get a release of `tendermint-rs` with #1245 included. Its exclusion from the `tendermint-rs` 0.34 backport regressed our debug output, causing a lot of debug spam for the last few months, and we've been hoping to avoid having to either rewrite all of our debug output or re-fork the dependency.

### Definition of "done"

A version of `tendermint-rs` with #1245 included is released and propagated through the rest of Informal's dep tree (particularly `ibc-rs`).

**Comment by erwanor** [comment]
Hey @mzabaluev, we're wondering if we could maybe cut this `0.29` release ahead of #1193 so that we can move forward with having `ed25519-consensus` (see #1245) so that this doesn't delay too much work on our side. I'm happy to cut the release myself, @thanethomson has granted me push rights on the repo, because I know y'all busy with comet

**Comment by adizere** [comment]
> maybe cut this 0.29 release ahead of https://github.com/informalsystems/tendermint-rs/pull/1193

@romac @mzabaluev what do you think? Seems very reasonable to cut 0.29 (without 1193), and then do another release after we're done with #1193 and whatever else will be necessary.

**Comment by romac** [comment]
> > maybe cut this 0.29 release ahead of #1193
> 
> @romac @mzabaluev what do you think? Seems very reasonable to cut 0.29 (without 1193), and then do another release after we're done with #1193 and whatever else will be necessary.

Agreed.
