### ISSUE TITLE
WebSocketClient::broadcast_tx_commit() does not work correctly when submitting concurrent async requests. 

### ISSUE THREAD

**Issue by ewoolsey** [informalsystems/tendermint-rs#1271]
submitting concurrent async txs in an async manner down not work how you would expect. It seems that somehow this function is blocking other tasks from also sending txs via the web socket. As a simple example, something like this does send two txs, but not at the same time as you would expect. The second one is not sent until the first tx returns.

```rust
let _ = join!(
   client.broadcast_tx_commit(tx_raw_1.to_bytes().unwrap()),
   client.broadcast_tx_commit(tx_raw_2.to_bytes().unwrap()),
);
```

**Comment by ewoolsey** [comment]
Anyone have any updates on this? It sort of defeats the entire point of using web socket no?

**Comment by thanethomson** [comment]
This is because the WebSocket driver (the component that interacts with a node via a TCP socket) is single-threaded and `broadcast_tx_commit` blocks until a transaction has been committed.

If you want to submit transactions to a node in parallel, the only way to do so is to open multiple WebSocket connections. Regardless of implementation, the WebSocket protocol itself doesn't support sending multiple transactions simultaneously - it's a single TCP connection, so requests and responses have to be pipelined. Even opening multiple TCP connections will be of limited use, however, because Tendermint Core/CometBFT-based nodes can only handle a couple of simultaneous WebSocket connections before their performance degrades.

In general, it is recommended to not use `broadcast_tx_commit` for anything but development/experimentation purposes. In fact, in CometBFT we're considering eventually removing the method in future entirely.

Please rather initiate a subscription for the results you're interested in and used `broadcast_tx_async`.

And with regard to the usefulness of it being an `async` interface, this allows thread-safe access to the underlying WebSocket driver within a broader `async` context. There haven't ever been any guarantees that requests will be processed in parallel within a single connection.

**Comment by ewoolsey** [comment]
@thanethomson thanks so much for the response. What you’re saying makes sense but the I don’t understand how CosmosJS can have exactly this functionality using websocket. I suppose I can make broadcast tx async work. Too bad since the commit method is much more convenient. Will broadcast_tx_sync have the same functionality where requests will not be sent concurrently but rather in series (I know they’ll be faster but I’d like them to be as fast as possible)

**Comment by thanethomson** [comment]
I'm no JS/TS expert and don't know cosmjs' code, but looking at their [WebSocket client implementation](https://github.com/cosmos/cosmjs/blob/95751316a0d15b3421058abbf3f95c06b40b68e6/packages/tendermint-rpc/src/rpcclients/websocketclient.ts#L133), it looks to me like they also queue their WebSocket requests.

> Too bad since the commit method is much more convenient.

Yes, `broadcast_tx_commit` was never intended for production use in the first place - it was primarily a tool for developers during testing only. It's unfortunate that it made its way into the public APIs and people started depending on it.

**Comment by romac** [comment]
Let's close this. Feel free to reopen it if further discussion is warranted.
