### ISSUE TITLE
Erroneous `Serialize` implementation on `abci::Event`

### ISSUE THREAD

**Issue by romac** [informalsystems/tendermint-rs#1299]
[…] Basically, there's a stray `derive(Serialize)` on Event, which declares an incorrect serialization format, incorrect because (a) it misses a `derive(Deserialize)`, so it's not usable, and (b) because it's derived from the domain type, it won't be compatible with anything else in the ecosystem. But it's a moot point because I dropped the commit. It could be good to do a review pass for `Serialize` derives; IMO it's a pretty dangerous pattern compared to the domain/serialization type pattern as with the proto infrastructure (where serialization is done on a dedicated facade type) because it secretly defines an additional external interface with long-lasting implications based off of an accident of the internal API.

_Originally posted by @hdevalence in https://github.com/informalsystems/tendermint-rs/issues/1288#issuecomment-1510009757_

**Comment by mzabaluev** [comment]
This has been fixed by restoring the `Deserialize` derive and making this serialization format the official as per JSON-RPC starting from 0.37. We don't explicitly care about other serializers, but the derives on the domain types provide the most straightforward data model for serde, so it should work reasonably well everywhere.
