### ISSUE TITLE
Light client time followup

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/tendermint-rs#137]
As per https://github.com/interchainio/tendermint-rs/issues/110#issuecomment-570755692:

- [x]  ensure that time in headers is monotonic, ie. `untrusted_header.bft_time() > trusted_header.bft_time()` in `verify_single` (see #142)
- [ ] check that the blockchain is not ahead of our local clock, ie. `untrusted_header.bft_time() < now + X` for every header we fetch

In theory, if we check that time is monotonic,  we only need to check that the highest height we're trying to sync to is not ahead of our local clock (ie. we don't need to check this for every header, since all the other headers are less than the highest one). However, if we only check for monotonic time after we've trusted a pivot header, its possible we would trust a pivot header who's time is too far ahead of our local clock, and hence might be outside the trusting period.

**Comment by Liamsi** [comment]
Note to myself: the spec calls `x` clockdrift and it is passed in as a parameter: https://github.com/tendermint/spec/blob/master/spec/consensus/light-client/verification.md#functions-1

Isn't there a weird edge case, where this method passes:
```
func isWithinTrustedPeriod(header Header,
                           trustingPeriod Duration,
                           now Time) bool {

    return header.Time + trustedPeriod > now
}
```
but only because the trusted header has `header.Time > now`? This shouldn't happen but shouldn't this still be covered by the spec too?
Note there is a check in the current Rust code:
https://github.com/interchainio/tendermint-rs/blob/a6f7c64e8214d5fbf32adee5ee3b6cbac09ee9da/tendermint/src/lite/verifier.rs#L43-L49
The name `DurationOutOfRange` stems from a time where we where using the [`duration_since` ](https://doc.rust-lang.org/std/time/struct.SystemTime.html#method.duration_since) method from SystemTime.

**Comment by Liamsi** [comment]
Also, isn't there a weird edge case, where this method passes:
```
func isWithinTrustedPeriod(header Header,
                           trustingPeriod Duration,
                           now Time) bool {

    return header.Time + trustedPeriod > now
}
```
but only because the trusted header has `header.Time > now`? This shouldn't happen but shouldn't this still be covered by the spec too?
Note there is a check in the current Rust code:
https://github.com/interchainio/tendermint-rs/blob/a6f7c64e8214d5fbf32adee5ee3b6cbac09ee9da/tendermint/src/lite/verifier.rs#L43-L49
The name `DurationOutOfRange` stems from a time where we where using the [`duration_since` ](https://doc.rust-lang.org/std/time/struct.SystemTime.html#method.duration_since) method from SystemTime.

**Comment by ebuchman** [comment]
Yes but that's why we need to ensure the header is not ahead of our local clock! ie `untrusted_header.bft_time() < now + X `

**Comment by Liamsi** [comment]
Ah, I think I see how this works: we make sure `untrusted_header.bft_time() < now + X` but also ensure `trusted_header.bft_time() < untrusted_header.bft_time() < now + X`. So we also have made sure `trusted_header.bft_time() < now` (or more precisely now+X) and the case I mentioned would have been caught by this without an extra check that `trusted_header.bft_time() <= now`.

**Comment by brapse** [comment]
This has been addressed and landed in master:
https://github.com/informalsystems/tendermint-rs/blob/740cb66e25ea38ac6b545bc9b4f9b294dcc23277/light-client/src/predicates.rs#L79-L120
