### ISSUE TITLE
SignedHeader impl needs to be updated

### ISSUE THREAD

**Issue by Shivani912** [informalsystems/tendermint-rs#145]
The Commit and CommitSig struct in Go code has been updated to [Commit](https://github.com/tendermint/tendermint/blob/master/types/block.go#L556) and [CommitSig](https://github.com/tendermint/tendermint/blob/master/types/block.go#L452) , while we are using the older version which looks like this:
`type Commit struct {
     BlockID BlockID,
     Precommits []*CommitSig
}
`and `type CommitSig Vote`

This makes the current Rust implementation incompatible with the current Go implementation and we cannot validate these SignedHeader.

**Comment by ebuchman** [comment]
Good stuff. Note that the latest Tendermint (v0.33) with the new commit diverges from what's running on the Gaia (Cosmos Hub) mainnet, and it will be at least a few months before those changes make it to Gaia. So if we need to update before then, we either need to give up compatibility with current Gaia or figure out a way to support both, which in principle we ought to be able to do anyways.

Also, related, I think there's a serious bug in the `voting_power_in` since we don't check if votes are actually for the right block_id, just if they're signed correctly for whatever block_id is in the vote. This would be solved with the new Commit structure, since vote's no longer specify the block_id, so it would have to be passed in from the Commit. So it seems the new Commit structure is not only smaller but safer!

Meanwhile, this is the kind of thing that could/should be checked in the new `validate` method.

**Comment by ebuchman** [comment]
Tracked by https://github.com/informalsystems/tendermint-rs/issues/184 and since closed.

> Also, related, I think there's a serious bug in the voting_power_in since we don't check if votes are actually for the right block_id, just if they're signed correctly for whatever block_id is in the vote. This would be solved with the new Commit structure, since vote's no longer specify the block_id, so it would have to be passed in from the Commit. So it seems the new Commit structure is not only smaller but safer!

Despite this, we still have a major bug in voting_power_in: https://github.com/informalsystems/tendermint-rs/issues/282
