### ISSUE TITLE
[pending Go changes] CommitSig validator address missing in Absent vote

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/tendermint-rs#260]
**Go implementation**
In CommitSig, in the BlockIDFlagAbsent type, the validator address field is expected to be missing.

**ADR-025**
The validator address field in Absent signatures should be present. (The validator address field should always be present.)

**Current Rust implemenation**
Rust implemented the ADR.

**Problem**
Tendermint-Rust is incompatible with Tendermint-Go.

**Solution**

* [done #277](https://github.com/informalsystems/tendermint-rs/issues/277) Add a compatibility code to the Rust implementation.
* [done](https://github.com/tendermint/tendermint/issues/4797) Add an issue to the Go repository
* [todo] Remove the compatibility code when the Go code adheres to ADR-025

**Comment by ebuchman** [comment]
Thanks @greg-szabo . If and when this is changed in the Go, it will be breaking, and we can open a new issue for it then, since it otherwise seems we've addressed it for now.

Also as per https://github.com/tendermint/tendermint/issues/4797#issuecomment-637875417, not sure this ever will be addressed, especially since we might look to remove ValidatorAddress from all CommitSigs!

Let's close this then?

**Comment by Liamsi** [comment]
I'm closing this. Feel free to re-open if you feel we should keep it open @greg-szabo.
