### ISSUE TITLE
Semantics of validator::Set

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/tendermint-rs#409]
I have a question wrt. to the semantics/implementation of [validator::Set](https://github.com/informalsystems/tendermint-rs/blob/547379daf73839883037b65f97d3ceb373f499b2/tendermint/src/validator.rs#L17), and in particular [validator::Set::new()](https://github.com/informalsystems/tendermint-rs/blob/547379daf73839883037b65f97d3ceb373f499b2/tendermint/src/validator.rs#L25). Actually, for me this feels more like a bug, but I need some clarification. The reason I am asking is because while writing my generator for Tendermint types I've stumbled into a behavior that was unexpected, and I've spent quite some time debugging the issue...

The question: **is it a well-established convention, that validators in a validator set should be sorted by their address?** This is how the implementation of `new()` works. My problem was that the validators in a JSON file were listed in a different order, therefore the hash computed for them, when `validator::Set` is deserialized using [parse_vals()](https://github.com/informalsystems/tendermint-rs/blob/547379daf73839883037b65f97d3ceb373f499b2/tendermint/src/validator.rs#L48) function, is different, than the hash computed from the same set, but constructed using [validator::Set::new()](https://github.com/informalsystems/tendermint-rs/blob/547379daf73839883037b65f97d3ceb373f499b2/tendermint/src/validator.rs#L25). Both ways should produce the same result, right? So, either of the two variants should be true:
1. it is a well established convention, and then all serialized validators should be in the right order. Then it should be explicitly documented somewhere.
2. it is not a convention, and then it's a bug in the deserialization function, which should actually also sort what it receives. 

Also, [validator::Set::new()](https://github.com/informalsystems/tendermint-rs/blob/547379daf73839883037b65f97d3ceb373f499b2/tendermint/src/validator.rs#L25) is modifying its argument, which somehow doesn't feel right for me -- a constructor should leave its arguments untouched, imho...

Will be grateful for clarifications.

**Comment by liamsi** [comment]
Validator sets in tendermint (v0.33.6) are indeed sorted by their address. In all places that return val sets (is that by convention?). Not sure if that counts as documentation but:
https://github.com/tendermint/tendermint/blob/9ee3e4896bf89c7f8481af0091f9511658a33043/types/validator_set.go#L33-L43

To make this more confusing, this is going to change with 0.34 though and they will be sorted by voting power:

https://github.com/tendermint/tendermint/blob/480b995a31727593f58b361af979054d17d84340/types/validator_set.go#L38-L51

As a side note, this plays into the discussion we had this afternoon about the types - in the light client library- could be more generic here (e.g. by being a trait) s.t. this would not matter for the light client core logic (maybe that is already the case). For your particular case this discussion is not too relevant though as it is a concrete type that gets deserialized. 

Maybe we should still sort on deserialzation? Not sure because usually the JSON that would come from any real tendermint instance would also be sorted (and in that case both `parse_vals()` and `Set::new` would return the same result).

**Comment by liamsi** [comment]
> Also, validator::Set::new() is modifying its argument, which somehow doesn't feel right for me -- a constructor should leave its arguments untouched, imho...

I also think that is weird but in rust at least that should not be a big problem because `pub fn new(mut vals: Vec<Info>)` will "consume" the original vector (it is not a reference), or, rather the parameter will be moved and can't not be accessed/used anymore (would be different if what was passed implemented the `Copy` trait but then it's not a problem because it is a copy). Maybe the doc comment should clarify this. It looks indeed suspicious :-D

**Comment by ebuchman** [comment]
Right, we need to ensure validator sets we're working with are always properly sorted. Currently (v0.33 of Tendermint Core and below) it's by address, but starting in v0.34 it will be by power. 

Serialized validators SHOULD be in the right order, and MUST be in the right order when they are hashed. 

This is documented in the Tendermint Go [rpc docs](https://docs.tendermint.com/master/rpc/#/Info/validators) and in the [Tendermint data structures spec](https://github.com/tendermint/spec/blob/master/spec/blockchain/blockchain.md#validatorshash), though in both cases it's been updated for the upcoming v0.34 version where validators are sorted by power, whereas currently in tendermint-rs and in Tendermint Go v0.33 it's still sorted by address.

Side note we also need to do a better job of versioning the specs/docs.

**Comment by ebuchman** [comment]
> My problem was that the validators in a JSON file were listed in a different order, therefore the hash computed for them

Where did these come from?

> ash computed for them, when validator::Set is deserialized using parse_vals() function, is different, than the hash computed from the same set, but constructed using validator::Set::new(). Both ways should produce the same result, right?

Right. Deserialize should probably sort what it received, or at least `hash()` should sort before hashing. Probably better if deserialize did it and we could ensure that every instance of `validator::Set` was sorted correctly.

**Comment by andrey-kuprianov** [comment]
Thanks for the info, @liamsi!

Vow, *that* is really confusing that such aspects change from one version to another...  Taking your input, here are my thoughts on the matter:

* If serialized objects are considered as external system interfaces, then they should probably be documented as such (e.g. if some external system which is not one of Tendermint go/rust implementations want to interact with it). And this documentation should be not in the source code comments.
* In any case, I would say, deserialization function should take care that the validators are sorted correctly upon entering the system.

Another point, this particular change from 0.33 into 0.34 is a breaking change, because the hashes will not match because of different orders on validators. How does it work then, when the running system is upgraded? The blocks as generated by the old implementation won't pass the validation in the new implementation then, right? (OK, I have found the answer to this question myself:) https://github.com/tendermint/tendermint/blob/master/UPGRADING.md)

Still, I think we should definitely sort correctly on deserialization -- otherwise the type invariant is violated. And probably check other Tendermint types for such possible violation. Because while this violation may be not dangerous (the validation will simply fail), others may be not so harmless...

**Comment by andrey-kuprianov** [comment]
> > My problem was that the validators in a JSON file were listed in a different order, therefore the hash computed for them
> 
> Where did these come from?

The JSON where validators are in the wrong order come from Apalache counterexample. Somehow from the semantics of a set, I didn;t think that they should be listed in any particular order...

**Comment by ebuchman** [comment]
> Vow, that is really confusing that such aspects change from one version to another

In general it shouldn't/doesn't, but once in a while the protocol goes through some breaking upgrades where it happens. Where in the midst of a series of upgrades.

> If serialized objects are considered as external system interfaces, then they should probably be documented as such (e.g. if some external system which is not one of Tendermint go/rust implementations want to interact with it). And this documentation should be not in the source code comments.

Agreed. Are the [rpc docs](https://docs.tendermint.com/master/rpc/#/Info/validators) and the [Tendermint data structures spec](https://github.com/tendermint/spec/blob/master/spec/blockchain/blockchain.md#validatorshash) not sufficient? Where would you have expected to find this?

> In any case, I would say, deserialization function should take care that the validators are sorted correctly upon entering the system.

Definitely.

> Another point, this particular change from 0.33 into 0.34 is a breaking change, because the hashes will not match because of different orders on validators. How does it work then, when the running system is upgraded? The blocks as generated by the old implementation won't pass the validation in the new implementation then, right?

Correct. Blockchains will need to be restarted from a different version. We have a history of doing this where we dump the state of the previous chain and start a new chain from height 0 beginning from the previous state. We've done these upgrades a few times on the Cosmos Hub. Hopefully we can evolve the Tendermint codebase to a point where we don't have to do this, ie. we can support multiple versions of the protocol in a single codebase, but it's currently too difficult.

> Somehow from the semantics of a set, I didn;t think that they should be listed in any particular order...

Doh, we've always called it a Validator Set but technically it's not just a set because it does needs to be hashed deterministically. Not sure what a better term might be ? Maybe `List` but it's pretty much standard across the industry to talk about "validator sets" and the "validator set hash" so not sure we can fix this one ...

**Comment by konnov** [comment]
> Right, we need to ensure validator sets we're working with are always properly sorted. Currently (v0.33 of Tendermint Core and below) it's by address, but starting in v0.34 it will be by power.

The validators of the same power should be sorted by addresses, right?

**Comment by andrey-kuprianov** [comment]
> Agreed. Are the [rpc docs](https://docs.tendermint.com/master/rpc/#/Info/validators) and the [Tendermint data structures spec](https://github.com/tendermint/spec/blob/master/spec/blockchain/blockchain.md#validatorshash) not sufficient? Where would you have expected to find this?

@ebuchman thanks for the links; yes, it's quite helpful. It's more that I am not still aware of all the source of documentation, than anything else.

> Doh, we've always called it a Validator Set but technically it's not just a set because it does needs to be hashed deterministically. Not sure what a better term might be ? Maybe List but it's pretty much standard across the industry to talk about "validator sets" and the "validator set hash" so not sure we can fix this one ...

I do think that `ValidatorSet` is a good name, it's just from the name only I had wrong assumptions on it. And of course it does need to be sorted in some order to get deterministic hashes.

> The validators of the same power should be sorted by addresses, right?

As pointed out by @liamsi,  [here](https://github.com/tendermint/tendermint/blob/480b995a31727593f58b361af979054d17d84340/types/validator_set.go#L38-L51) it's documented, albeit only in a comment, that they are first sorted by the voting power (descending), and then by address (ascending). And this should be actually reflected in the [rpc docs](https://docs.tendermint.com/master/rpc/#/Info/validators), which says "Validators are sorted by voting power", and in the [Tendermint data structures spec](https://github.com/tendermint/spec/blob/master/spec/blockchain/blockchain.md#validatorshash), which says "Note the validators are sorted by their voting power before computing the MerkleRoot."

**Comment by ebuchman** [comment]
> The validators of the same power should be sorted by addresses, right?

Yes.

> As pointed out by @liamsi, here it's documented, albeit only in a comment, that they are first sorted by the voting power (descending), and then by address (ascending). And this should be actually reflected in the rpc docs, which says "Validators are sorted by voting power", and in the Tendermint data structures spec, which says "Note the validators are sorted by their voting power before computing the MerkleRoot."

Great point. Want to open an issue on the tendermint/tendermint repo with this suggestion? I'm sure a PR would be welcome too if you like.

And then I guess we can close this one?

**Comment by andrey-kuprianov** [comment]
I will follow up with an issue/PR on tendermint/tendermint, and probably with a PR here to sort the validators also in a deserialization function, but will do it on Monday -- don't want to do it in a hurry.

What I am also going to do, but over a longer period of time, is to search for some implicit type invariants in the code, and check whether they are satisfied on all the paths... just curious whether some interesting bugs will pop up;) Also should be fun to try to catch such things automatically with MBT.
