### ISSUE TITLE
light-client: Fork Detection Evidence Submission Review

### ISSUE THREAD

**Issue by brapse** [informalsystems/tendermint-rs#415]
The light client is expected to submit different evidence to full nodes according to: https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-047-handling-evidence-from-light-client.md

We need to go through our implementation of the light client and ensure that:
- We submit all possible evidence under the correct circumstances
- We have test cases

**Comment by ebuchman** [comment]
More details described in #499 - maybe we can consolidate these two issues.

**Comment by josef-widder** [comment]
Yes. We should consolidate the issues, and plan for moving forward.

There is a related point: For IBC, the tendermint lightclient (ICS 07, but the text os outdated compared to the code), expects a different form of evidence than the one an on-chain full node expects. For the relayer computing this evidence is in general more complicated due to the limited information at the handler, and the limited interface. So this issue needs to be addressed

- in the context of am individual lightnode
- in the context of a relayer
