### ISSUE TITLE
Multi peer malicious validator set is not detected

### ISSUE THREAD

**Issue by OStevan** [informalsystems/tendermint-rs#417]
When running the `bisection/multi-peer/malicious-validator-set.json` both primary and witness manage to verify the light block without detecting the malicious validator set. In this case the hashes or headers from two peers are wrong so a fork is detected and the test passes but neither of the two peers are marked as faulty as they do not fail on verification.

**Comment by romac** [comment]
@Shivani912 Is that the expected behavior here?

**Comment by Shivani912** [comment]
@OStevan @romac I think we badly need to discuss what goes in the description of these tests - it's ambiguous or should at least say what the description is meant for. On the test, so there's a `trusted_validator_set` for initial few heights and then it changes after a certain height. When you ask the light client to verify header at `height=11` with `trusted_header` at `height=1` in bisection mode, `primary_provider` gives a header with set of validators that is different than the one we have in our `trusted_store`. But, `witness` gives a header signed off by the exact same validator set we already trust (from `trusted_validator_set`). Now this is the case where old validator set starts to misbehave. So this can be seen as a fork too, because both headers are valid. This could also result into an error that no witness found for the data we got from primary and should abort - that's what Go Light Client does. So it's hard to say what specific error it must fail on because this is very implementation specific. That is one major reason for not having expectations on specific error types in these tests.

**Comment by OStevan** [comment]
@Shivani912 @romac Sorry, I made a mistake when comparing. There was a bug in my code. However, I agree it would be useful to have some more details in the tests why they fail.
