### ISSUE TITLE
light-client: consolidate and delete old implementations

### ISSUE THREAD

**Issue by xla** [informalsystems/tendermint-rs#437]
With the advent of the `light-client` crate, which was meant to superseed prior implementations we now have a large corpus of code that is outdated and should be sun-setted. Keep maintaining this parts like `lite` and `lite_impl` is gonna add significant overhead that is unnecessary at this stage of the project.

These modules should be carefully evaluated to extract knowledge, implementation details which are worth preserving w.r.t. #416.

**Comment by xla** [comment]
@yihuang @joe-bowman this could be relevant to you.###

**Comment by liamsi** [comment]
I'm strongly in favour of this. While @ebuchman rightfully mentioned that other projects are already using the `lite` module (cc @yihuang @joe-bowman), I think this it will confusing with the next release (there is `lite`, `lite_impl`, `light-client`, `light-node` etc).

Also, I already added a ⚠️ ️deprecation warning ⚠️ in one the last releases:https://github.com/informalsystems/tendermint-rs/blob/master/CHANGES.md#0140-2020-06-19

Note, that there already is a related issue #342 (we might want to deduplicate the deduplication issues too).

> These modules should be carefully evaluated to extract knowledge, implementation details which are worth preserving w.r.t. #416.

I agree that the current `lite` module might help inform the steps towards #416 but I think it could be OK to have this captured here and in version control instead of keeping the code around.
