### ISSUE TITLE
light-client: clock drift for trusting period

### ISSUE THREAD

**Issue by OStevan** [informalsystems/tendermint-rs#523]
When reading the Predicate checks I noticed that there is a conflict with a comment and the code regarding usage of [clock drift](https://github.com/informalsystems/tendermint-rs/blob/da9e1773247afccadb855c21afb5601a84f85558/light-client/src/predicates.rs#L99) from #474 . This specifically says we adjust for clock drifts but that parameter is not passed in nor used.

Should we adjust or not in this case? It was already [mentioned](https://github.com/informalsystems/tendermint-rs/pull/474/files/68188bcf2cbf2ebf71cd67cbed5a66a1f78a756f#r460276838) but currently, with the comment it seems to be confusing.

**Comment by Shivani912** [comment]
Ay, very good catch! No we're not adjusting for clock drift right now. I think issue #478 contains further discussion on whether we should or not. I'd suggest to update the comment for the current state of code for now and wait for a decision on how to account for clock drifts since it's a larger issue.

**Comment by xla** [comment]
Can we merge this into #478 then? @OStevan @Shivani912

**Comment by Shivani912** [comment]
Yeah, I think we should link it there @xla

**Comment by ebuchman** [comment]
Lets close this for #478
