### ISSUE TITLE
Make the signature on Proposal optional field?

### ISSUE THREAD

**Issue by tomtau** [informalsystems/tendermint-rs#626]
In TM: https://github.com/tendermint/tendermint/blob/master/consensus/state.go#L1089
`SignProposalRequest` is created without the signature (the raw type will have `vec![0]` as the signature), so https://github.com/informalsystems/tendermint-rs/blob/master/tendermint/src/proposal/sign_proposal.rs#L24 will fail, because the "signature" has an incorrect size.
should this be patched here to account for this case, or should Tendermint be patched (change the protobuf type or "pad" the empty signature field to the expected length)? @greg-szabo @marbar3778

**Comment by tomtau** [comment]
given 0.34 is a sort of finalised, I guess here?
If so, will it go to 0.17.1: https://github.com/informalsystems/tendermint-rs/pull/624 ?

**Comment by tomtau** [comment]
another option is if `SignProposalRequest` contains `CanonicalProposal` instead of `Proposal`

**Comment by tomtau** [comment]
the same for `SignVoteRequest`

**Comment by greg-szabo** [comment]
Hi tomtau! Apologies on the slow turnaround on this, I just noticed it yesterday.

A few weeks ago, this struct came up in one of our internal discussions and I asked "if there's no proposal in a proposal request, what is its purpose?". And the answer was a resounding "you pass butter" (i.e.: nothing).

Our domain knowledge tells us that a ProposalRequest should always have a proposal. Which begs the question: so what's the problem with the signature.

I think the real problem is that the types describing proposals, signing requests and signatures are decoupled wrong. A proposal request should always contain a proposal, but it should never contain a signature (the request is used to generate the signature). (A SignedProposalResponse should always contain a signature.) But in our current model, the proposal and the signature are in the same struct, hence a proposal request will have a signature (which is invalid).

You see that in my logic above, I explicitly try and not use optional elements. This should be one of our axioms for domain types (I'll get around and write an ADR about it one of these days). In most cases, using `Option<>` hides a misunderstanding or a problematic implementation detail. (Domain types are great at surfacing those with these rules.)

So, I have a few ideas how to deal with this:
1. The quickest way is to make the Proposal.Signature optional (again). This makes sense from a domain knowledge perspective. Not all proposals are signed at all times, even in memory. It hides the problem.
2. An alternative approach is to define the `[0; LENGTH]` vector as the Default and empty vector or a "missing signature". This is how it is done in the Merkle Hash struct. In both the Hash's and Signature's case, Go might define (in worst case: send us) an invalid `vec![]`. The conversion traits (`TryFrom<Raw>` and `Into<Raw>`) explicitly check for this edge case and convert an `[0;LENGTH]` into an empty `vec![]` and vice versa. This sounds more complex but the same logic has to be applied in the first case too, only to the optional value.
3. We could (and eventually should) decouple the `Proposal` struct into the correct `Proposal` (missing the Signature field) struct and a `SignedProposal` struct (= Proposal + Signature). I think this is the solution we should gravitate toward, eventually. I believe we're still grasping all the details of the changes for 0.17, so I'm mentioning this for the sake of completeness and we should revisit it later.

I'm leaning toward number 2 for now. I'll create a PR to show the exact solution.

Feel free to add more comments and ideas, I'm happy to implement other solutions too.

(Also, yes, this applies exactly the same to `VoteRequest`, as you mentioned.)

**Comment by tomtau** [comment]
> We could (and eventually should) decouple the Proposal struct into the correct Proposal (missing the Signature field) struct and a SignedProposal struct (= Proposal + Signature).

AFAIK `CanonicalProposal` is pretty much `Proposal` without the `Signature` field.

> How does this sound? If you like this version, I can merge it or we can keep discussing alternatives.

I think it's all right; probably the simplest workaround for the time being.

**Comment by greg-szabo** [comment]
> AFAIK CanonicalProposal is pretty much Proposal without the Signature field.

Yeah, we should raise it to the Go team (or whoever manages the protobuf types right now) to change the SignProposalRequest to hold a CanonicalProposal.

Maybe I'll do that later, a few discrepancies are already surfacing in the protobuf types.
