### ISSUE TITLE
RPC broadcast_tx_commit() response parsing error with successful transaction

### ISSUE THREAD

**Issue by ancazamfir** [informalsystems/tendermint-rs#667]
## Description
Changed `ibc-rs` to submit transactions using `broadcast_tx_commit` and get this error with successful transaction:
```tx error: RPC error: RPC error: Parse error. Invalid JSON: parse error at line 17 column 49 (code: -32700)```

It is caused by non empty strings for `data` and `log` fields in the response.

**Comment by ancazamfir** [comment]
Here is one response response [example](https://github.com/informalsystems/tendermint-rs/files/5517460/broadcast_tx_commit.txt). If pasted in [this test file](https://github.com/informalsystems/tendermint-rs/blob/master/rpc/tests/support/broadcast_tx_commit.json) it will show the error.

**Comment by thanethomson** [comment]
Is the `data` field supposed to contain base64-encoded data? It looks like the `Data` struct is being serialized/deserialized as hexadecimal. See [here](https://github.com/informalsystems/tendermint-rs/blob/master/tendermint/src/abci/data.rs#L43).

**Comment by greg-szabo** [comment]
Here're a few observations I gathered while looking at this issue:
* The data field is considered a blob by Tendermint that should not be interpreted more than a `Vec<u8>`. It could be any data rendered by the ABCI application.
* The `kvstore` application we use in our integration testing most probably encodes a hex string and possibly that's why the FromStr and Display traits implement that conversion. These traits are then automatically used for serialization/deserialization.
* Unfortunately, I was not able to recreate a response from the kvstore app that would populate the data field. (Admittedly, I only ran a few `curl` commands to try. We can get back to this.) It's possible that the serialization implementation is a shot in the dark.
* I was not able to get a response from the Cosmos-SDK yet either that populates the data field. I think it would make it much easier if you could provide the Request that you're sending to the endpoint.
* I would be careful of using `broadcast_tx_commit` instead of `broadcast_tx_sync`. The [Swagger documentation](https://docs.tendermint.com/master/rpc/#/Tx/broadcast_tx_commit) points out that the former is for debugging and troubleshooting. Regular code should use sync or async. I'm not sure how well the documentation is maintained, but it's worth noting.

I'll look into the Go code tomorrow and try to find where and how the data field is encoded in different apps.

I think one thing the Tendermint code should do is remove the hex-string serialization and just use plain Vec<u8> (or maybe even string) and let the app do the decoding of the field. (In this case IBC.)

The log issue is slightly easier, although I don't have the full picture there either. The example log you show is a string-escaped array of JSON structs. (It starts with an opening bracket instead of an opening curly brace.) Looking at the Rust code, it seems, only one JSON struct is expected for deserialization, so the opening bracket throws off the deserializer. It's also an interesting question whether Serde can deal with escaped strings or not.

I'll have to check what the intention was in the Go code here too. The current response doesn't seem to be directly JSON-deserializable, but there's always hope.

**Comment by thanethomson** [comment]
If the `data` field contains a format specific to an ABCI app, why not just make it `Option<String>` and let the caller decode it as they wish?

It's weird though that Tendermint in Go models the `data` field as being of type `HexBytes` (see [here](https://github.com/tendermint/tendermint/blob/master/rpc/core/types/responses.go#L162)), but the field value @ancazamfir's getting in the `broadcast_tx_commit` response is `ChYKFGNvbm5lY3Rpb25fb3Blbl9pbml0` - those certainly don't look like hex bytes to me. Seems like something weird's going on in the serialization there?

**Comment by ancazamfir** [comment]
> It's weird though that Tendermint in Go models the data field as being of type HexBytes (see here), but the field value @ancazamfir's getting in the broadcast_tx_commit response is ChYKFGNvbm5lY3Rpb25fb3Blbl9pbml0 ...

Isn't the commit response struct this one https://github.com/tendermint/tendermint/blob/a399fae100d07b506c6065a5e3f82c14746fb317/rpc/core/types/responses.go#L170?

**Comment by thanethomson** [comment]
> Isn't the commit response struct this one https://github.com/tendermint/tendermint/blob/a399fae100d07b506c6065a5e3f82c14746fb317/rpc/core/types/responses.go#L170?

Actually yes, sorry, you're right. And the `data` field is defined [here](https://github.com/tendermint/tendermint/blob/master/abci/types/types.pb.go#L1922) in the Protobuf types.

Where does that get serialized though?

**Comment by thanethomson** [comment]
> Where does that get serialized though?

I think I found it: by default, `bytes` type gets serialized into a base64-encoded string, as per: https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by greg-szabo** [comment]
The above fix will correctly deser/ser abci::Data as Base64-encoded string.

I'm still chasing the Log thing.

**Comment by greg-szabo** [comment]
The above will fix the `Log` too. `Log` should either be empty, a string or an array. It should be an UTF-8 decodable String in JSON.
