### ISSUE TITLE
Unpin funty 1.1.0 dependency

### ISSUE THREAD

**Issue by thanethomson** [informalsystems/tendermint-rs#818]
Once the issue outlined in #816 is fixed, we need to remove the explicit dependency on `funty` v1.1.0.

**What's the definition of "done" for this issue?**

When tendermint-rs compiles successfully with the latest version of `funty` and without explicitly depending on a specific version of it.

**Comment by tony-iqlusion** [comment]
The next release of `k256` (which will hopefully happen in early March) uses `elliptic-curve` v0.9 -> `ff` v0.9 -> `bitvec` v0.20, and I believe the `funty` issue is occurring due to `bitvec` v0.19.

(Also note that if https://github.com/zkcrypto/ff/pull/42 were to land it would be possible to remove the `bitvec` dependency entirely, although I'm not sure if it's being used elsewhere or not)

**Comment by tony-iqlusion** [comment]
There's a workaround for this in `elliptic-curve` v0.8.5 so you no-longer need to pin it yourself: https://github.com/RustCrypto/traits/pull/554

**Comment by thanethomson** [comment]
There no longer seems to be any `funty` dependency in our dependency tree:

```bash
> cargo tree --all-features --invert funty
error: package ID specification `funty` did not match any packages
```
